local M = {}

local function run_lsp_action(action)
  return function() require('neocraft.features.lsp')[action]() end
end

local function notify_specific_mode_only(action, mode)
  return function() vim.notify(action .. ' works from ' .. mode .. ' mode only', vim.log.levels.INFO) end
end

local function feedkeys(keys)
  return function() vim.api.nvim_feedkeys(vim.keycode(keys), 'm', false) end
end

local function action_items()
  local actions = {
    {
      group = 'Buffers',
      mode = 'n',
      key = '<C-[>',
      invoke = "require('neocraft.features.workspace').previous_buffer()",
      desc = 'Previous buffer',
      run = function() require('neocraft.features.workspace').previous_buffer() end,
    },
    {
      group = 'Buffers',
      mode = 'n',
      key = '<C-]>',
      invoke = "require('neocraft.features.workspace').next_buffer()",
      desc = 'Next buffer',
      run = function() require('neocraft.features.workspace').next_buffer() end,
    },
    {
      group = 'Buffers',
      mode = 'n',
      key = '<C-c>',
      invoke = "require('neocraft.features.workspace').delete_buffer()",
      desc = 'Delete current buffer',
      run = function() require('neocraft.features.workspace').delete_buffer() end,
    },
    {
      group = 'Buffers',
      mode = 'n',
      key = '<C-n>',
      invoke = "require('neocraft.features.workspace').new_buffer()",
      desc = 'New buffer',
      run = function() require('neocraft.features.workspace').new_buffer() end,
    },
    {
      group = 'Pickers',
      mode = 'n',
      key = '<C-p>',
      invoke = "require('neocraft.features.pickers').actions()",
      desc = 'Open action picker',
      run = function() require('neocraft.features.pickers').actions() end,
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '<Esc>',
      invoke = "require('neocraft.features.editor').clear_on_escape()",
      desc = 'Multiple clearing actions',
      run = function() require('neocraft.features.editor').clear_on_escape() end,
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '<C-s>',
      invoke = "require('neocraft.features.workspace').save()",
      desc = 'Save current file',
      run = function() require('neocraft.features.workspace').save() end,
    },
    {
      group = 'Editing',
      mode = 'i,x',
      key = '<C-s>',
      invoke = "require('neocraft.features.workspace').save_and_normal_mode()",
      desc = 'Save and return to Normal mode',
      run = function() require('neocraft.features.workspace').save_and_normal_mode() end,
    },
    {
      group = 'Editing',
      mode = 'i,n,s,x',
      key = '<C-S-s>',
      invoke = "require('neocraft.features.workspace').save_without_formatting()",
      desc = 'Save without formatting',
      run = function() require('neocraft.features.workspace').save_without_formatting() end,
    },
    {
      group = 'Git',
      mode = 'n',
      key = '<C-Space>',
      invoke = "require('neocraft.features.git').toggle_overlay()",
      desc = 'Toggle diff overlay',
      run = function() require('neocraft.features.git').toggle_overlay() end,
    },
    {
      group = 'Git',
      mode = 'n,x',
      key = 'go',
      invoke = "require('neocraft.features.git').open()",
      desc = 'Git open item at cursor',
      run = function() require('neocraft.features.git').open() end,
    },
    {
      group = 'Git',
      mode = 'n',
      key = '[h',
      invoke = "require('neocraft.features.git').goto_hunk('prev')",
      desc = 'Previous git hunk',
      run = feedkeys('[h'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = ']h',
      invoke = "require('neocraft.features.git').goto_hunk('next')",
      desc = 'Next git hunk',
      run = feedkeys(']h'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = '[H',
      invoke = "require('neocraft.features.git').goto_hunk('first')",
      desc = 'First git hunk',
      run = feedkeys('[H'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = ']H',
      invoke = "require('neocraft.features.git').goto_hunk('last')",
      desc = 'Last git hunk',
      run = feedkeys(']H'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = '[g',
      invoke = "require('neocraft.features.git').prev_pending_file(false)",
      desc = 'Previous unstaged git file',
      run = feedkeys('[g'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = ']g',
      invoke = "require('neocraft.features.git').next_pending_file(false)",
      desc = 'Next unstaged git file',
      run = feedkeys(']g'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = '[G',
      invoke = "require('neocraft.features.git').prev_pending_file(true)",
      desc = 'Previous staged git file',
      run = feedkeys('[G'),
    },
    {
      group = 'Git',
      mode = 'n',
      key = ']G',
      invoke = "require('neocraft.features.git').next_pending_file(true)",
      desc = 'Next staged git file',
      run = feedkeys(']G'),
    },
    {
      group = 'Git',
      mode = 'n,o,x',
      key = 'gh',
      invoke = 'gh',
      desc = 'Apply hunk',
      run = feedkeys('gh'),
    },
    {
      group = 'Git',
      mode = 'n,o,x',
      key = 'gH',
      invoke = 'gH',
      desc = 'Reset hunk',
      run = feedkeys('gH'),
    },
    {
      group = 'Editing',
      mode = 'n,x',
      key = '<M-j>',
      invoke = "require('neocraft.features.editing').move_lines_down()",
      desc = 'Move line or selection down',
      run = function() require('neocraft.features.editing').move_lines_down() end,
    },
    {
      group = 'Editing',
      mode = 'n,x',
      key = '<M-k>',
      invoke = "require('neocraft.features.editing').move_lines_up()",
      desc = 'Move line or selection up',
      run = function() require('neocraft.features.editing').move_lines_up() end,
    },
    {
      group = 'Editing',
      mode = 'x',
      key = '<C-Space>',
      invoke = '<C-Space>',
      desc = 'Increase selection',
      run = notify_specific_mode_only('<C-Space>', 'Visual'),
    },
    {
      group = 'Editing',
      mode = 'x',
      key = '<BS>',
      invoke = '<BS>',
      desc = 'Decrease selection',
      run = notify_specific_mode_only('<BS>', 'Visual'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '<M-h>',
      invoke = "require('neocraft.features.editing').scroll_view_left()",
      desc = 'Scroll view left',
      run = function() require('neocraft.features.editing').scroll_view_left() end,
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '<M-H>',
      invoke = "require('neocraft.features.editing').scroll_view_half_left()",
      desc = 'Scroll view half-screen left',
      run = function() require('neocraft.features.editing').scroll_view_half_left() end,
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '<M-l>',
      invoke = "require('neocraft.features.editing').scroll_view_right()",
      desc = 'Scroll view right',
      run = function() require('neocraft.features.editing').scroll_view_right() end,
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '<M-L>',
      invoke = "require('neocraft.features.editing').scroll_view_half_right()",
      desc = 'Scroll view half-screen right',
      run = function() require('neocraft.features.editing').scroll_view_half_right() end,
    },
    {
      group = 'Editing',
      mode = 'i,t,c',
      key = '<M-h>',
      invoke = "require('neocraft.features.editing').move_cursor_left()",
      desc = 'Move left',
      run = notify_specific_mode_only('<M-h>', 'Insert/Terminal/Command'),
    },
    {
      group = 'Editing',
      mode = 'i,t,c',
      key = '<M-l>',
      invoke = "require('neocraft.features.editing').move_cursor_right()",
      desc = 'Move right',
      run = notify_specific_mode_only('<M-l>', 'Insert/Terminal/Command'),
    },
    {
      group = 'Editing',
      mode = 'i,t',
      key = '<M-j>',
      invoke = "require('neocraft.features.editing').move_cursor_down()",
      desc = 'Move down',
      run = notify_specific_mode_only('<M-j>', 'Insert/Terminal'),
    },
    {
      group = 'Editing',
      mode = 'i,t',
      key = '<M-k>',
      invoke = "require('neocraft.features.editing').move_cursor_up()",
      desc = 'Move up',
      run = notify_specific_mode_only('<M-k>', 'Insert/Terminal'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = '[p',
      invoke = '[p',
      desc = 'Paste above',
      run = feedkeys('[p'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = ']p',
      invoke = ']p',
      desc = 'Paste below',
      run = feedkeys(']p'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = 'gV',
      invoke = 'gV',
      desc = 'Reselect last paste/change',
      run = feedkeys('gV'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = 's',
      invoke = 's',
      desc = 'Start jump',
      run = feedkeys('s'),
    },
    {
      group = 'Editing',
      mode = 'n,x',
      key = 'ys',
      invoke = 'ys',
      desc = 'Add surrounding',
      run = feedkeys('ys'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = 'ds',
      invoke = 'ds',
      desc = 'Delete surrounding',
      run = feedkeys('ds'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = 'cs',
      invoke = 'cs',
      desc = 'Change surrounding',
      run = feedkeys('cs'),
    },
    {
      group = 'Editing',
      mode = 'n',
      key = 'yss',
      invoke = 'yss',
      desc = 'Add surrounding to line',
      run = feedkeys('yss'),
    },
    {
      group = 'Editing',
      mode = 'x',
      key = 'S',
      invoke = 'S',
      desc = 'Surround selection',
      run = notify_specific_mode_only('S', 'Visual'),
    },
    {
      group = 'Session',
      mode = 'i,n,s,x',
      key = '<C-S-r>',
      invoke = "require('neocraft.features.editor').restart_neovim()",
      desc = 'Restart Neovim',
      run = function() require('neocraft.features.editor').restart_neovim() end,
    },
    {
      group = 'Session',
      mode = 'n',
      key = '<C-q>',
      invoke = "require('neocraft.features.editor').quit_neovim()",
      desc = 'Quit Neovim',
      run = function() require('neocraft.features.editor').quit_neovim() end,
    },
    {
      group = 'Editing',
      mode = 't',
      key = '<Esc><Esc>',
      invoke = "require('neocraft.features.terminal').exit_terminal_mode()",
      desc = 'Exit terminal mode',
      run = notify_specific_mode_only('<Esc><Esc>', 'Terminal'),
    },
    {
      group = 'Windows',
      mode = 'n',
      key = '[<Tab>',
      invoke = '[<Tab>',
      desc = 'Previous tab',
      run = feedkeys('[<Tab>'),
    },
    {
      group = 'Windows',
      mode = 'n',
      key = ']<Tab>',
      invoke = ']<Tab>',
      desc = 'Next tab',
      run = feedkeys(']<Tab>'),
    },
    {
      group = 'Windows',
      mode = 'n',
      key = '<C-CR>',
      invoke = "require('neocraft.features.workspace').toggle_maximized()",
      desc = 'Toggle maximized window',
      run = function() require('neocraft.features.workspace').toggle_maximized() end,
    },
    {
      group = 'Windows',
      mode = 'n,t',
      key = '<C-h>',
      invoke = "require('neocraft.features.workspace').focus_left()",
      desc = 'Focus window to the left',
      run = function() require('neocraft.features.workspace').focus_left() end,
    },
    {
      group = 'Windows',
      mode = 'n,t',
      key = '<C-j>',
      invoke = "require('neocraft.features.workspace').focus_down()",
      desc = 'Focus window below',
      run = function() require('neocraft.features.workspace').focus_down() end,
    },
    {
      group = 'Windows',
      mode = 'n,t',
      key = '<C-k>',
      invoke = "require('neocraft.features.workspace').focus_up()",
      desc = 'Focus window above',
      run = function() require('neocraft.features.workspace').focus_up() end,
    },
    {
      group = 'Windows',
      mode = 'n,t',
      key = '<C-l>',
      invoke = "require('neocraft.features.workspace').focus_right()",
      desc = 'Focus window to the right',
      run = function() require('neocraft.features.workspace').focus_right() end,
    },
    {
      group = 'Windows',
      mode = 'n,t',
      key = '<C-/>',
      invoke = "require('neocraft.features.terminal').toggle()",
      desc = 'Toggle floating terminal',
      run = function() require('neocraft.features.terminal').toggle() end,
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'K',
      invoke = 'K',
      desc = 'Hover documentation',
      run = feedkeys('K'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'gd',
      invoke = 'gd',
      desc = 'Go to definition / tag',
      run = feedkeys('gd'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'gD',
      invoke = 'gD',
      desc = 'Go to declaration / TS: Go to source definition',
      run = feedkeys('gD'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'grr',
      invoke = 'grr',
      desc = 'Go to references',
      run = feedkeys('grr'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'gri',
      invoke = 'gri',
      desc = 'Go to implementation',
      run = feedkeys('gri'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'grt',
      invoke = 'grt',
      desc = 'Go to type definition',
      run = feedkeys('grt'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'gR',
      invoke = "require('neocraft.features.lsp').typescript_file_references()",
      desc = 'TS: Go to file references',
      run = run_lsp_action('typescript_file_references'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = 'grn',
      invoke = 'grn',
      desc = 'Rename symbol',
      run = feedkeys('grn'),
    },
    {
      group = 'Coding',
      mode = 'n,x',
      key = 'gra',
      invoke = 'gra',
      desc = 'Code actions',
      run = feedkeys('gra'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cO',
      invoke = "require('neocraft.features.lsp').typescript_organize_imports()",
      desc = 'TS: Organize imports',
      run = run_lsp_action('typescript_organize_imports'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cO',
      invoke = "require('neocraft.features.lsp').python_organize_imports()",
      desc = 'Py: Organize imports',
      run = run_lsp_action('python_organize_imports'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cM',
      invoke = "require('neocraft.features.lsp').typescript_add_missing_imports()",
      desc = 'TS: Add missing imports',
      run = run_lsp_action('typescript_add_missing_imports'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cU',
      invoke = "require('neocraft.features.lsp').typescript_remove_unused_imports()",
      desc = 'TS: Remove unused imports',
      run = run_lsp_action('typescript_remove_unused_imports'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cR',
      invoke = "require('neocraft.features.lsp').typescript_restart()",
      desc = 'TS: Restart server',
      run = run_lsp_action('typescript_restart'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cV',
      invoke = "require('neocraft.features.lsp').typescript_select_version()",
      desc = 'TS: Select workspace version',
      run = run_lsp_action('typescript_select_version'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>cV',
      invoke = "require('neocraft.features.lsp').python_select_venv()",
      desc = 'Py: Select virtual environment',
      run = run_lsp_action('python_select_venv'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '<Leader>clt',
      invoke = "require('neocraft.features.lsp').typescript_open_log()",
      desc = 'TS: Open server log',
      run = run_lsp_action('typescript_open_log'),
    },
    {
      group = 'Coding',
      mode = 'i',
      key = '<C-k>',
      invoke = 'vim.lsp.buf.signature_help()',
      desc = 'Signature help',
      run = vim.lsp.buf.signature_help,
    },
    {
      group = 'Coding',
      mode = 'i',
      key = '<C-Space>',
      invoke = '<C-Space>',
      desc = 'Manually trigger completions',
      run = notify_specific_mode_only('<C-Space>', 'Insert'),
    },
    {
      group = 'Coding',
      mode = 'i',
      key = '<C-e>',
      invoke = '<C-e>',
      desc = 'Close completions / Accept to EOL',
      run = notify_specific_mode_only('<C-e>', 'Insert'),
    },
    {
      group = 'Coding',
      mode = 'i',
      key = '<C-]>',
      invoke = '<C-]>',
      desc = 'Dismiss active inline completion',
      run = notify_specific_mode_only('<C-]>', 'Insert'),
    },
    {
      group = 'Coding',
      mode = 'i',
      key = '<M-[>',
      invoke = '<M-[>',
      desc = 'Previous inline completion',
      run = notify_specific_mode_only('<M-[>', 'Insert'),
    },
    {
      group = 'Coding',
      mode = 'i',
      key = '<M-]>',
      invoke = '<M-]>',
      desc = 'Next / Retrigger inline completion',
      run = notify_specific_mode_only('<M-]>', 'Insert'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '[e',
      invoke = '[e',
      desc = 'Jump to previous error',
      run = feedkeys('[e'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = ']e',
      invoke = ']e',
      desc = 'Jump to next error',
      run = feedkeys(']e'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '[w',
      invoke = '[w',
      desc = 'Jump to previous warning',
      run = feedkeys('[w'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = ']w',
      invoke = ']w',
      desc = 'Jump to next warning',
      run = feedkeys(']w'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = '[d',
      invoke = '[w',
      desc = 'Jump to previous diagnostic',
      run = feedkeys('[d'),
    },
    {
      group = 'Coding',
      mode = 'n',
      key = ']d',
      invoke = ']w',
      desc = 'Jump to next diagnostic',
      run = feedkeys(']d'),
    },
    {
      group = 'Windows',
      mode = 'n',
      key = '<C-Left>',
      invoke = "require('neocraft.features.workspace').resize_left()",
      desc = 'Decrease window width',
      run = function() require('neocraft.features.workspace').resize_left() end,
    },
    {
      group = 'Windows',
      mode = 'n',
      key = '<C-Down>',
      invoke = "require('neocraft.features.workspace').resize_down()",
      desc = 'Decrease window height',
      run = function() require('neocraft.features.workspace').resize_down() end,
    },
    {
      group = 'Windows',
      mode = 'n',
      key = '<C-Up>',
      invoke = "require('neocraft.features.workspace').resize_up()",
      desc = 'Increase window height',
      run = function() require('neocraft.features.workspace').resize_up() end,
    },
    {
      group = 'Windows',
      mode = 'n',
      key = '<C-Right>',
      invoke = "require('neocraft.features.workspace').resize_right()",
      desc = 'Increase window width',
      run = function() require('neocraft.features.workspace').resize_right() end,
    },
  }

  for _, item in ipairs(actions) do
    item.group = item.group or 'Other'
    item.mode = item.mode or 'Not set'
    item.key = item.key or 'Not set'
    item.text = string.format(
      '%-8s │ %-12s │ %-50s │ %-14s │ %s',
      item.mode,
      item.key,
      item.desc,
      item.group,
      item.invoke
    )
  end

  table.sort(actions, function(a, b)
    if a.group == b.group then return a.invoke < b.invoke end
    return a.group < b.group
  end)

  return actions
end

local function action_preview(buf_id, item)
  if type(item) ~= 'table' then return end

  local lines = {
    'Group: ' .. (item.group or 'Other'),
    'Mode: ' .. (item.mode or 'Not set'),
    'Keymap: ' .. (item.key or 'Not set'),
    'Invoke: ' .. (item.invoke or ''),
    '',
    item.desc or '',
  }

  vim.bo[buf_id].filetype = 'text'
  vim.api.nvim_buf_set_lines(buf_id, 0, -1, false, lines)
end

-- Starts 'actions' custom picker, showing available actions that can be performed on the current buffer or context.
function M.actions()
  return require('mini.pick').start({
    source = {
      items = action_items,
      name = 'Actions',
      preview = action_preview,
      choose = function(item)
        if type(item) ~= 'table' or type(item.run) ~= 'function' then return end
        vim.schedule(item.run)
      end,
    },
  })
end

return M
